name: Release a new version

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Setup go
        uses: https://github.com/actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: stable
      - name: Prepare environment
        run: |
          go install github.com/tc-hib/go-winres@c4d55a3dfc2e22a4a9fb95ae0280ce106daadce9
      - name: Run GoReleaser
        uses: https://github.com/goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6
        with:
          version: "latest"
          args: release --clean
        env:
          GITEA_TOKEN: ${{ secrets.IMLONGHAO_BOT_TOKEN }}
          CLUBLOG_API_KEY: ${{ secrets.CLUBLOG_API_KEY }}
          GORELEASER_FORCE_TOKEN: gitea
      - name: Sync to GitHub
        run: |
          pip install requests
          python scripts/sync-to-github.py
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_RELEASE_TOKEN }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
